org.gradle.java.home=E:\\Java\\jbr-25.0.4-windows-x64-b508.27
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.88
ldlib2_version=26.2.2.41.a

mod_id=elementlib
mod_name=ElementLib
mod_license=NC-Open 1.0 (Non-Commercial Open) - https://github.com/Violet-Molder/elementlib
mod_version=26.2.0.3
mod_group_id=com.linweiyun.elementlib
